from __future__ import annotations
from typing import Protocol, Optional, Sequence

from core.types import GeneratedMedia


class Storage(Protocol):
    """Единственная точка персистентности. Реализация — aiosqlite; для тестов — in-memory.

    Все методы — контракты ядра, tgbot работает только через них.
    """

    # юзеры и настройки
    async def ensure_user(self, user_id: int, locale: str = "ru") -> None: ...
    async def user_locale(self, user_id: int) -> str: ...
    async def set_user_locale(self, user_id: int, locale: str) -> None: ...
    async def user_stats(self, user_id: int) -> dict: ...

    # чаты
    async def ensure_chat(self, chat_id: int, title: str = "") -> None: ...
    async def chat_enabled(self, chat_id: int) -> bool: ...
    async def set_chat_enabled(self, chat_id: int, enabled: bool) -> None: ...

    # квоты/история
    async def usage_count(self, user_id: int, unit: str, window: str) -> int: ...
    async def chat_usage_count(self, chat_id: int, unit: str, window: str) -> int: ...
    async def record_usage(self, user_id: int, chat_id: int | None, unit: str) -> None: ...
    async def window_seconds_left(self, window: str) -> int: ...
    async def save_generation(self, user_id: int, chat_id: int | None, media: GeneratedMedia, file_id: str = "") -> None: ...
    async def recent_generations(self, user_id: int, limit: int = 8) -> Sequence[dict]: ...
    async def last_media_file_id(self, user_id: int) -> Optional[str]: ...
    async def set_last_media_file_id(self, user_id: int, file_id: str) -> None: ...
    async def save_original_prompt(self, user_id: int, prompt: str) -> None: ...
    async def original_prompt(self, user_id: int) -> Optional[str]: ...
    async def save_last_prompt(self, user_id: int, prompt: str) -> None: ...
    async def last_prompt(self, user_id: int) -> Optional[str]: ...

    # настройки чата (из референса Rose: per-chat настройки в БД, не в коде)
    async def chat_setting(self, chat_id: int, key: str) -> str: ...
    async def set_chat_setting(self, chat_id: int, key: str, value: str) -> None: ...
